// Auto-generated by scripts/generate-images.js — do not edit manually
// Run: node scripts/generate-images.js to refresh after generating new images

type ImageSource = number;

export const STORY_IMAGES: Record<string, ImageSource> = {
  // forest_of_shadows
  'assets/stories/forest_of_shadows/images/consumed_by_shadows.png': require('../../assets/stories/forest_of_shadows/images/consumed_by_shadows.png'),
  'assets/stories/forest_of_shadows/images/dark_path.png': require('../../assets/stories/forest_of_shadows/images/dark_path.png'),
  'assets/stories/forest_of_shadows/images/escaped_with_amulet.png': require('../../assets/stories/forest_of_shadows/images/escaped_with_amulet.png'),
  'assets/stories/forest_of_shadows/images/forest_entrance.png': require('../../assets/stories/forest_of_shadows/images/forest_entrance.png'),
  'assets/stories/forest_of_shadows/images/forest_spirits_guide.png': require('../../assets/stories/forest_of_shadows/images/forest_spirits_guide.png'),
  'assets/stories/forest_of_shadows/images/hermit_camp.png': require('../../assets/stories/forest_of_shadows/images/hermit_camp.png'),
  'assets/stories/forest_of_shadows/images/hermit_lore.png': require('../../assets/stories/forest_of_shadows/images/hermit_lore.png'),
  'assets/stories/forest_of_shadows/images/lit_path.png': require('../../assets/stories/forest_of_shadows/images/lit_path.png'),
  'assets/stories/forest_of_shadows/images/ruined_shrine.png': require('../../assets/stories/forest_of_shadows/images/ruined_shrine.png'),
  'assets/stories/forest_of_shadows/images/safe_exit.png': require('../../assets/stories/forest_of_shadows/images/safe_exit.png'),
  'assets/stories/forest_of_shadows/images/spirits_awaken.png': require('../../assets/stories/forest_of_shadows/images/spirits_awaken.png'),
  // test_story
  'assets/stories/test_story/images/conditional_scene.png': require('../../assets/stories/test_story/images/conditional_scene.png'),
  'assets/stories/test_story/images/death_ending.png': require('../../assets/stories/test_story/images/death_ending.png'),
  'assets/stories/test_story/images/good_ending.png': require('../../assets/stories/test_story/images/good_ending.png'),
  'assets/stories/test_story/images/item_scene.png': require('../../assets/stories/test_story/images/item_scene.png'),
  'assets/stories/test_story/images/start.png': require('../../assets/stories/test_story/images/start.png'),
  // the_mists_of_bravora
  'assets/stories/the_mists_of_bravora/images/scene_001.png': require('../../assets/stories/the_mists_of_bravora/images/scene_001.png'),
  'assets/stories/the_mists_of_bravora/images/scene_002.png': require('../../assets/stories/the_mists_of_bravora/images/scene_002.png'),
  'assets/stories/the_mists_of_bravora/images/scene_003.png': require('../../assets/stories/the_mists_of_bravora/images/scene_003.png'),
  'assets/stories/the_mists_of_bravora/images/scene_004.png': require('../../assets/stories/the_mists_of_bravora/images/scene_004.png'),
  'assets/stories/the_mists_of_bravora/images/scene_005.png': require('../../assets/stories/the_mists_of_bravora/images/scene_005.png'),
  'assets/stories/the_mists_of_bravora/images/scene_005b.png': require('../../assets/stories/the_mists_of_bravora/images/scene_005b.png'),
  'assets/stories/the_mists_of_bravora/images/scene_006.png': require('../../assets/stories/the_mists_of_bravora/images/scene_006.png'),
  'assets/stories/the_mists_of_bravora/images/scene_007.png': require('../../assets/stories/the_mists_of_bravora/images/scene_007.png'),
  'assets/stories/the_mists_of_bravora/images/scene_008.png': require('../../assets/stories/the_mists_of_bravora/images/scene_008.png'),
  'assets/stories/the_mists_of_bravora/images/scene_009.png': require('../../assets/stories/the_mists_of_bravora/images/scene_009.png'),
  'assets/stories/the_mists_of_bravora/images/scene_010.png': require('../../assets/stories/the_mists_of_bravora/images/scene_010.png'),
  'assets/stories/the_mists_of_bravora/images/scene_011.png': require('../../assets/stories/the_mists_of_bravora/images/scene_011.png'),
  'assets/stories/the_mists_of_bravora/images/scene_death.png': require('../../assets/stories/the_mists_of_bravora/images/scene_death.png'),
};
